import type { Space } from './types';

export const spaces: Space[] = [
  {
    id: 'urban-oasis-desk',
    name: 'Urban Hot Desk',
    description: 'A vibrant, open-plan hot desk area perfect for freelancers and remote workers. Enjoy our high-speed Wi-Fi and unlimited coffee.',
    capacity: 1,
    amenities: ['wifi', 'coffee', 'printing'],
    images: ['https://img.freepik.com/free-photo/side-view-businesswoman-using-sign-language-video-call_23-2148740302.jpg?semt=ais_hybrid&w=740&q=80', 'https://picsum.photos/800/600?random=2'],
    pricing: {
      hourly: 10,
      daily: 50,
      weekly: 200,
      monthly: 12000,
    },
    type: 'hot_desk',
  },
  {
    id: 'huddle-pods',
    name: 'Huddle Pods',
    description: 'Ideal for 2–4 person huddles, these pods are perfect for small team discussions, meetings, or quick interviews. Offering a balance of privacy and comfortable seating, they create an effective space for focused working sessions within a collaborative environment.',
    capacity: 4,
    amenities: ['wifi', 'coffee', 'whiteboard'],
    images: ['https://ik.imagekit.io/72dpiweb/vidak/slir/w-h520-q90/3693/', 'https://picsum.photos/800/600?random=10'],
    pricing: {
      hourly: 0,
      daily: 0,
      monthly: 25000,
    },
    type: 'huddle_pods',
  },
  {
    id: 'collaborate-hub-room',
    name: 'Collaborate Meeting Room',
    description: 'A modern meeting room equipped with a large screen, whiteboard, and video conferencing facilities. Perfect for team meetings and client presentations.',
    capacity: 8,
    amenities: ['wifi', 'coffee', 'whiteboard', 'kitchen'],
    images: ['https://img.freepik.com/free-photo/studio-arrangement-work_23-2151976835.jpg?semt=ais_incoming&w=740&q=80', 'https://picsum.photos/800/600?random=6'],
    pricing: {
      hourly: 750,
      daily: 500,
    },
    type: 'meeting_room',
  },
  {
    id: 'quiet-corner-desk',
    name: 'Quiet Corner Dedicated Desk',
    description: 'A serene and dedicated desk for focused work. Ideal for individuals needing a dedicated space.',
    capacity: 1,
    amenities: ['wifi', 'coffee', 'printing'],
    images: ['https://img.freepik.com/premium-photo/comfortable-home-office-corner-with-laptop-computer-tablet-office-supplies-with-coffee-cup_67155-4579.jpg', 'https://picsum.photos/800/600?random=16'],
    pricing: {
      hourly: 0,
      daily: 0,
      monthly: 22000,
    },
    type: 'dedicated_desk',
  },
  {
    id: 'sunlight-studio',
    name: 'Sunlight Studio',
    description: 'A bright and airy private office filled with natural light. Comes with ergonomic furniture and dedicated parking.',
    capacity: 4,
    amenities: ['wifi', 'coffee', 'parking'],
    images: ['https://img.freepik.com/free-photo/modern-equipped-computer-lab_23-2149241198.jpg?semt=ais_incoming&w=740&q=80', 'https://picsum.photos/800/600?random=8'],
    pricing: {
      hourly: 0,
      daily: 0,
      monthly: 95000,
    },
    type: 'private_office',
  },
  {
    id: 'boardroom-pro',
    name: 'The Boardroom Pro',
    description: 'An executive boardroom for up to 20 people. Features premium A/V equipment, a private kitchenette, and stunning city views.',
    capacity: 20,
    amenities: ['wifi', 'coffee', 'printing', 'kitchen', 'whiteboard'],
    images: ['https://picsum.photos/800/600?random=11', 'https://picsum.photos/800/600?random=12'],
    pricing: {
      hourly: 150,
      daily: 1000,
    },
    type: 'meeting_room',
  },
];
